In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
path_to_file = "E:\study materials\python\05_Deep Learning - Udemy\FINAL_TF2_FILES\TF_2_Notebooks_and_Data\06-NLP-and-Text-Data\shakespeare.txt"

In [3]:
text = open(r"E:\study materials\python\05_Deep Learning - Udemy\FINAL_TF2_FILES\TF_2_Notebooks_and_Data\06-NLP-and-Text-Data\shakespeare.txt",'r').read()

In [4]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [5]:
vocab = sorted(set(text))

In [6]:
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [7]:
len(vocab)

84

In [8]:
for pair in enumerate(vocab):
    print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


In [9]:
char_to_ind = {char : ind for ind,char in enumerate(vocab)}

In [10]:
char_to_ind['H']

33

In [11]:
ind_to_char = np.array(vocab)

In [12]:
ind_to_char[33]

'H'

In [13]:
encoded_text = np.array([char_to_ind[c] for c in text] )

In [14]:
encoded_text.shape

(5445609,)

In [15]:
sample = text[:500]

In [16]:
sample

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [17]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [18]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [19]:
line = 'From fairest creatures we desire increase'

In [20]:
len(line)

41

In [21]:
lines = '''
From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
'''

In [22]:
len(lines)

133

In [23]:
seq_len = 120

In [24]:
total_num_seq = len(text) // (seq_len + 1)

In [25]:
total_num_seq

45005

In [26]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

In [27]:
type(char_dataset)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [28]:
sequences = char_dataset.batch(seq_len + 1, drop_remainder=True)

In [29]:
def create_seq_targets(seq):
    input_txt = seq[:-1]
    target_txt = seq[1:]
    return input_txt, target_txt

In [30]:
dataset = sequences.map(create_seq_targets)

In [31]:
for input_txt,target_txt in dataset.take(1):
    print(input_txt.numpy())
    print("".join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    print("".join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [32]:
batch_size = 128

In [33]:
buffer_size = 10000

In [34]:
dataset = dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True)

In [35]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int32, name=None), TensorSpec(shape=(128, 120), dtype=tf.int32, name=None))>

In [36]:
vocab_size = len(vocab)

In [37]:
vocab_size

84

In [38]:
embed_dim = 64

In [39]:
rnn_neurons = 1026

In [40]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [41]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1, ignore_class=None)
    Computes the sparse categorical crossentropy loss.
    
    Standalone usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    >>> y_true = [[[ 0,  2],
    ...            [-1, -1]],
    ...           [[ 0,  2],
    ...            [-1, -1]]]
    >>> y_pred = [[[[1.0, 0.0, 0.0], [0.0, 0.0, 1.0]],
    ...             [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]],
    ...           [[[1.0, 0.0, 0.0], [0.0, 0.5, 0.5]],
    ...            [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(
    ...   y_true, y_pred, ignore_class=-1)
    >>> loss.numpy()
    array([[[2.384

In [42]:
def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [43]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,GRU,Dense

In [44]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dim,batch_input_shape=[batch_size, None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    # Final Dense Layer to Predict
    model.add(Dense(vocab_size))
    model.compile(optimizer='adam', loss=sparse_cat_loss) 
    return model

In [45]:
model = create_model(
  vocab_size = vocab_size,
  embed_dim=embed_dim,
  rnn_neurons=rnn_neurons,
  batch_size=batch_size)

In [46]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (128, None, 64)           5376      
                                                                 
 gru (GRU)                   (128, None, 1026)         3361176   
                                                                 
 dense (Dense)               (128, None, 84)           86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [47]:
for input_example_batch , target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)

In [48]:
example_batch_predictions.shape

TensorShape([128, 120, 84])

In [49]:
example_batch_predictions[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[ 5.3274292e-03, -6.9450559e-03,  3.1870694e-03, ...,
         1.4209410e-03, -7.1764332e-03, -1.4953173e-03],
       [-2.0743483e-03, -1.1858188e-03,  3.6631497e-03, ...,
        -5.6039006e-03, -1.3082029e-02,  3.0025053e-03],
       [-4.5957807e-03, -4.7849445e-03,  4.6500866e-03, ...,
        -5.5731256e-03, -1.0842167e-02, -3.9592935e-03],
       ...,
       [-7.0549385e-03,  3.9714077e-03, -6.5835181e-04, ...,
         6.2013289e-04, -8.6092524e-04,  1.4014797e-03],
       [-5.1813810e-03,  1.6519752e-03, -4.6076346e-04, ...,
         4.5391433e-03,  1.1319082e-05,  9.2106598e-04],
       [-7.0128948e-03,  5.2191429e-03, -2.0250294e-03, ...,
        -3.3793948e-03,  3.4133364e-03, -6.0578068e-03]], dtype=float32)>

In [50]:
sampled_indices = tf.random.categorical(example_batch_predictions[0],num_samples=1)

In [51]:
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[30],
       [27],
       [28],
       [14],
       [22],
       [15],
       [19],
       [47],
       [43],
       [34],
       [64],
       [57],
       [72],
       [49],
       [58],
       [64],
       [ 1],
       [30],
       [59],
       [26],
       [34],
       [43],
       [64],
       [40],
       [63],
       [26],
       [52],
       [43],
       [37],
       [54],
       [57],
       [24],
       [25],
       [77],
       [30],
       [ 2],
       [83],
       [28],
       [56],
       [17],
       [48],
       [20],
       [52],
       [49],
       [59],
       [ 6],
       [ 1],
       [37],
       [74],
       [38],
       [37],
       [59],
       [ 6],
       [ 3],
       [16],
       [75],
       [63],
       [ 4],
       [67],
       [50],
       [49],
       [64],
       [26],
       [28],
       [55],
       [21],
       [62],
       [11],
       [39],
       [48],
       [55],
       [24],
       [48],
   

In [53]:
sampled_indices = tf.squeeze(sampled_indices, axis=1).numpy()

In [54]:
ind_to_char[sampled_indices]

array(['E', 'B', 'C', '3', ';', '4', '8', 'V', 'R', 'I', 'i', 'b', 'q',
       'X', 'c', 'i', ' ', 'E', 'd', 'A', 'I', 'R', 'i', 'O', 'h', 'A',
       '[', 'R', 'L', '_', 'b', '>', '?', 'v', 'E', '!', '}', 'C', 'a',
       '6', 'W', '9', '[', 'X', 'd', '(', ' ', 'L', 's', 'M', 'L', 'd',
       '(', '"', '5', 't', 'h', '&', 'l', 'Y', 'X', 'i', 'A', 'C', '`',
       ':', 'g', '0', 'N', 'W', '`', '>', 'W', 'L', 'Z', 'o', 'P', 'V',
       'X', 'Z', 'P', '7', '1', '4', 'y', 'v', 'T', '1', ']', 'd', '-',
       'o', 'y', '1', 'K', 'R', 'O', 'd', 'E', 'l', '\n', '|', 'X', 'x',
       'c', 'f', '7', 'p', ':', 'n', 'B', 'B', '_', '-', 'v', '?', '9',
       'T', 'e', 'V'], dtype='<U1')

In [ ]:
epochs = 30
model.fit(dataset,epochs=epochs)